package com.im.freechat.di;

import android.content.res.Resources;
import com.im.freechat.domain.usecase.auth.e;
import com.im.freechat.domain.usecase.chat.q;
import com.im.freechat.domain.usecase.chat.r;
import com.im.freechat.domain.usecase.chat.s;
import com.im.freechat.domain.usecase.contact.f;
import com.im.freechat.domain.usecase.members.h;
import com.im.freechat.domain.usecase.messages.b;
import com.im.freechat.domain.usecase.messages.d;
import com.im.freechat.domain.usecase.messages.i;
import com.im.freechat.domain.usecase.messages.j;
import com.im.freechat.domain.usecase.messages.k;
import com.im.freechat.domain.usecase.messages.n;
import com.im.freechat.domain.usecase.messages.o;
import com.im.freechat.domain.usecase.messages.p;
import com.im.freechat.media.audio.c;
import com.im.freechat.ui.chat.chat_selector.ChatSelectorViewModel;
import com.im.freechat.ui.chat.chatdetails.ChatDetailsViewModel;
import com.im.freechat.ui.chat.history.HistoryTabViewModel;
import com.im.freechat.ui.chat.userprofile.UserProfileViewModel;
import java.util.List;
import kotlin.Metadata;
import kotlin.Pair;
import kotlin.Unit;
import kotlin.collections.CollectionsKt__CollectionsKt;
import kotlin.jvm.functions.Function1;
import kotlin.jvm.functions.Function2;
import kotlin.jvm.internal.Intrinsics;
import kotlin.jvm.internal.Lambda;
import kotlin.jvm.internal.Reflection;
import m8.g;
import org.koin.core.definition.Kind;
import org.koin.core.registry.c;
import org.koin.core.scope.Scope;

/* compiled from: ChatModule.kt */
@Metadata(bv = {}, d1 = {"\u0000\f\n\u0002\u0018\u0002\n\u0002\u0010\u0002\n\u0002\b\u0002\u0010\u0002\u001a\u00020\u0001*\u00020\u0000H\n¢\u0006\u0004\b\u0002\u0010\u0003"}, d2 = {"Lx8/a;", "", "a", "(Lx8/a;)V"}, k = 3, mv = {1, 7, 1})
/* loaded from: classes3.dex */
final class ChatModuleKt$chatModule$1 extends Lambda implements Function1<x8.a, Unit> {

    /* renamed from: a  reason: collision with root package name */
    public static final ChatModuleKt$chatModule$1 f41233a = new ChatModuleKt$chatModule$1();

    /* JADX INFO: Access modifiers changed from: package-private */
    /* compiled from: ChatModule.kt */
    @Metadata(bv = {}, d1 = {"\u0000\u0012\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\u0010\u0004\u001a\u00020\u0003*\u00020\u00002\u0006\u0010\u0002\u001a\u00020\u0001H\n¢\u0006\u0004\b\u0004\u0010\u0005"}, d2 = {"Lorg/koin/core/scope/Scope;", "Ly8/a;", "it", "Lcom/im/freechat/ui/chat/chatdetails/ChatDetailsViewModel;", "a", "(Lorg/koin/core/scope/Scope;Ly8/a;)Lcom/im/freechat/ui/chat/chatdetails/ChatDetailsViewModel;"}, k = 3, mv = {1, 7, 1})
    /* loaded from: classes3.dex */
    public static final class a extends Lambda implements Function2<Scope, y8.a, ChatDetailsViewModel> {

        /* renamed from: a  reason: collision with root package name */
        public static final a f41234a = new a();

        a() {
            super(2);
        }

        @Override // kotlin.jvm.functions.Function2
        @g
        /* renamed from: a */
        public final ChatDetailsViewModel invoke(@g Scope viewModel, @g y8.a it) {
            Intrinsics.checkNotNullParameter(viewModel, "$this$viewModel");
            Intrinsics.checkNotNullParameter(it, "it");
            return new ChatDetailsViewModel((k) viewModel.p(Reflection.getOrCreateKotlinClass(k.class), null, null), (r) viewModel.p(Reflection.getOrCreateKotlinClass(r.class), null, null), (e) viewModel.p(Reflection.getOrCreateKotlinClass(e.class), null, null), (com.im.freechat.domain.usecase.chat.e) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.chat.e.class), null, null), (j) viewModel.p(Reflection.getOrCreateKotlinClass(j.class), null, null), (b) viewModel.p(Reflection.getOrCreateKotlinClass(b.class), null, null), (n) viewModel.p(Reflection.getOrCreateKotlinClass(n.class), null, null), (c) viewModel.p(Reflection.getOrCreateKotlinClass(c.class), null, null), (com.im.freechat.domain.usecase.chat.a) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.chat.a.class), null, null), (p4.e) viewModel.p(Reflection.getOrCreateKotlinClass(p4.e.class), null, null), (h) viewModel.p(Reflection.getOrCreateKotlinClass(h.class), null, null), (com.im.freechat.domain.usecase.contact.b) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.contact.b.class), null, null), (f) viewModel.p(Reflection.getOrCreateKotlinClass(f.class), null, null), (com.im.freechat.domain.usecase.contact.a) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.contact.a.class), null, null), (com.im.freechat.domain.usecase.contact.j) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.contact.j.class), null, null), (com.im.freechat.domain.h) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.h.class), null, null), (i) viewModel.p(Reflection.getOrCreateKotlinClass(i.class), null, null), (q) viewModel.p(Reflection.getOrCreateKotlinClass(q.class), null, null), (com.im.freechat.domain.usecase.chat.f) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.chat.f.class), null, null), (com.im.freechat.domain.usecase.messages.c) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.messages.c.class), null, null), (o) viewModel.p(Reflection.getOrCreateKotlinClass(o.class), null, null), (com.im.freechat.domain.usecase.chat.j) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.chat.j.class), null, null), (p) viewModel.p(Reflection.getOrCreateKotlinClass(p.class), null, null), (com.im.freechat.domain.usecase.currentuser.h) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.currentuser.h.class), null, null), (com.im.freechat.domain.usecase.currentuser.b) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.currentuser.b.class), null, null), (com.im.freechat.utils.f) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.utils.f.class), null, null), (com.im.freechat.domain.usecase.messages.a) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.messages.a.class), null, null), (com.im.freechat.domain.usecase.messages.f) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.messages.f.class), null, null), (com.im.freechat.domain.usecase.messages.e) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.messages.e.class), null, null), (d) viewModel.p(Reflection.getOrCreateKotlinClass(d.class), null, null), (s) viewModel.p(Reflection.getOrCreateKotlinClass(s.class), null, null), (com.im.freechat.domain.usecase.messages.g) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.messages.g.class), null, null), (com.im.freechat.domain.n) viewModel.p(Reflection.getOrCreateKotlinClass(com.im.freechat.domain.n.class), null, null), (Resources) viewModel.p(Reflection.getOrCreateKotlinClass(Resources.class), null, null));
        }
    }

    ChatModuleKt$chatModule$1() {
        super(1);
    }

    public final void a(@g x8.a module) {
        List emptyList;
        List emptyList2;
        List emptyList3;
        List emptyList4;
        List emptyList5;
        List emptyList6;
        List emptyList7;
        List emptyList8;
        List emptyList9;
        List emptyList10;
        List emptyList11;
        List emptyList12;
        List emptyList13;
        List emptyList14;
        List emptyList15;
        List emptyList16;
        List emptyList17;
        List emptyList18;
        List emptyList19;
        List emptyList20;
        List emptyList21;
        List emptyList22;
        List emptyList23;
        List emptyList24;
        List emptyList25;
        List emptyList26;
        List emptyList27;
        List emptyList28;
        List emptyList29;
        List emptyList30;
        List emptyList31;
        List emptyList32;
        List emptyList33;
        List emptyList34;
        List emptyList35;
        List emptyList36;
        List emptyList37;
        List emptyList38;
        List emptyList39;
        List emptyList40;
        List emptyList41;
        List emptyList42;
        List emptyList43;
        List emptyList44;
        List emptyList45;
        List emptyList46;
        Intrinsics.checkNotNullParameter(module, "$this$module");
        a aVar = a.f41234a;
        c.a aVar2 = org.koin.core.registry.c.f92526e;
        z8.c a10 = aVar2.a();
        Kind kind = Kind.Factory;
        emptyList = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar3 = new org.koin.core.instance.a(new org.koin.core.definition.a(a10, Reflection.getOrCreateKotlinClass(ChatDetailsViewModel.class), null, aVar, kind, emptyList));
        module.p(aVar3);
        new Pair(module, aVar3);
        ChatModuleKt$chatModule$1$invoke$$inlined$viewModelOf$1 chatModuleKt$chatModule$1$invoke$$inlined$viewModelOf$1 = new ChatModuleKt$chatModule$1$invoke$$inlined$viewModelOf$1();
        z8.c a11 = aVar2.a();
        emptyList2 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar4 = new org.koin.core.instance.a(new org.koin.core.definition.a(a11, Reflection.getOrCreateKotlinClass(ChatSelectorViewModel.class), null, chatModuleKt$chatModule$1$invoke$$inlined$viewModelOf$1, kind, emptyList2));
        module.p(aVar4);
        new Pair(module, aVar4);
        ChatModuleKt$chatModule$1$invoke$$inlined$viewModelOf$2 chatModuleKt$chatModule$1$invoke$$inlined$viewModelOf$2 = new ChatModuleKt$chatModule$1$invoke$$inlined$viewModelOf$2();
        z8.c a12 = aVar2.a();
        emptyList3 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar5 = new org.koin.core.instance.a(new org.koin.core.definition.a(a12, Reflection.getOrCreateKotlinClass(UserProfileViewModel.class), null, chatModuleKt$chatModule$1$invoke$$inlined$viewModelOf$2, kind, emptyList3));
        module.p(aVar5);
        new Pair(module, aVar5);
        ChatModuleKt$chatModule$1$invoke$$inlined$viewModelOf$3 chatModuleKt$chatModule$1$invoke$$inlined$viewModelOf$3 = new ChatModuleKt$chatModule$1$invoke$$inlined$viewModelOf$3();
        z8.c a13 = aVar2.a();
        emptyList4 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar6 = new org.koin.core.instance.a(new org.koin.core.definition.a(a13, Reflection.getOrCreateKotlinClass(HistoryTabViewModel.class), null, chatModuleKt$chatModule$1$invoke$$inlined$viewModelOf$3, kind, emptyList4));
        module.p(aVar6);
        new Pair(module, aVar6);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$1 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$1 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$1();
        z8.c a14 = aVar2.a();
        emptyList5 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar7 = new org.koin.core.instance.a(new org.koin.core.definition.a(a14, Reflection.getOrCreateKotlinClass(r.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$1, kind, emptyList5));
        module.p(aVar7);
        new Pair(module, aVar7);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$2 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$2 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$2();
        z8.c a15 = aVar2.a();
        emptyList6 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar8 = new org.koin.core.instance.a(new org.koin.core.definition.a(a15, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.chat.f.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$2, kind, emptyList6));
        module.p(aVar8);
        new Pair(module, aVar8);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$3 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$3 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$3();
        z8.c a16 = aVar2.a();
        emptyList7 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar9 = new org.koin.core.instance.a(new org.koin.core.definition.a(a16, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.downloads.a.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$3, kind, emptyList7));
        module.p(aVar9);
        new Pair(module, aVar9);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$4 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$4 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$4();
        z8.c a17 = aVar2.a();
        emptyList8 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar10 = new org.koin.core.instance.a(new org.koin.core.definition.a(a17, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.chat.j.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$4, kind, emptyList8));
        module.p(aVar10);
        new Pair(module, aVar10);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$5 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$5 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$5();
        z8.c a18 = aVar2.a();
        emptyList9 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar11 = new org.koin.core.instance.a(new org.koin.core.definition.a(a18, Reflection.getOrCreateKotlinClass(q.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$5, kind, emptyList9));
        module.p(aVar11);
        new Pair(module, aVar11);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$6 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$6 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$6();
        z8.c a19 = aVar2.a();
        emptyList10 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar12 = new org.koin.core.instance.a(new org.koin.core.definition.a(a19, Reflection.getOrCreateKotlinClass(com.im.freechat.ui.chat.chatdetails.messagelist.b.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$6, kind, emptyList10));
        module.p(aVar12);
        new Pair(module, aVar12);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$7 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$7 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$7();
        z8.c a20 = aVar2.a();
        emptyList11 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar13 = new org.koin.core.instance.a(new org.koin.core.definition.a(a20, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.downloads.d.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$7, kind, emptyList11));
        module.p(aVar13);
        new Pair(module, aVar13);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$8 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$8 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$8();
        z8.c a21 = aVar2.a();
        emptyList12 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar14 = new org.koin.core.instance.a(new org.koin.core.definition.a(a21, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.downloads.b.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$8, kind, emptyList12));
        module.p(aVar14);
        new Pair(module, aVar14);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$9 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$9 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$9();
        z8.c a22 = aVar2.a();
        emptyList13 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar15 = new org.koin.core.instance.a(new org.koin.core.definition.a(a22, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.downloads.c.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$9, kind, emptyList13));
        module.p(aVar15);
        new Pair(module, aVar15);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$10 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$10 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$10();
        z8.c a23 = aVar2.a();
        emptyList14 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar16 = new org.koin.core.instance.a(new org.koin.core.definition.a(a23, Reflection.getOrCreateKotlinClass(j.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$10, kind, emptyList14));
        module.p(aVar16);
        new Pair(module, aVar16);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$11 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$11 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$11();
        z8.c a24 = aVar2.a();
        emptyList15 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar17 = new org.koin.core.instance.a(new org.koin.core.definition.a(a24, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.messages.g.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$11, kind, emptyList15));
        module.p(aVar17);
        new Pair(module, aVar17);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$12 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$12 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$12();
        z8.c a25 = aVar2.a();
        emptyList16 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar18 = new org.koin.core.instance.a(new org.koin.core.definition.a(a25, Reflection.getOrCreateKotlinClass(com.im.freechat.ui.chat.history.k.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$12, kind, emptyList16));
        module.p(aVar18);
        new Pair(module, aVar18);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$13 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$13 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$13();
        z8.c a26 = aVar2.a();
        emptyList17 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar19 = new org.koin.core.instance.a(new org.koin.core.definition.a(a26, Reflection.getOrCreateKotlinClass(n.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$13, kind, emptyList17));
        module.p(aVar19);
        new Pair(module, aVar19);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$14 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$14 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$14();
        z8.c a27 = aVar2.a();
        emptyList18 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar20 = new org.koin.core.instance.a(new org.koin.core.definition.a(a27, Reflection.getOrCreateKotlinClass(b.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$14, kind, emptyList18));
        module.p(aVar20);
        new Pair(module, aVar20);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$15 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$15 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$15();
        z8.c a28 = aVar2.a();
        emptyList19 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar21 = new org.koin.core.instance.a(new org.koin.core.definition.a(a28, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.messages.h.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$15, kind, emptyList19));
        module.p(aVar21);
        new Pair(module, aVar21);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$16 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$16 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$16();
        z8.c a29 = aVar2.a();
        emptyList20 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar22 = new org.koin.core.instance.a(new org.koin.core.definition.a(a29, Reflection.getOrCreateKotlinClass(k.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$16, kind, emptyList20));
        module.p(aVar22);
        new Pair(module, aVar22);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$17 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$17 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$17();
        z8.c a30 = aVar2.a();
        emptyList21 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar23 = new org.koin.core.instance.a(new org.koin.core.definition.a(a30, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.messages.f.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$17, kind, emptyList21));
        module.p(aVar23);
        new Pair(module, aVar23);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$18 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$18 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$18();
        z8.c a31 = aVar2.a();
        emptyList22 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar24 = new org.koin.core.instance.a(new org.koin.core.definition.a(a31, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.messages.e.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$18, kind, emptyList22));
        module.p(aVar24);
        new Pair(module, aVar24);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$19 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$19 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$19();
        z8.c a32 = aVar2.a();
        emptyList23 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar25 = new org.koin.core.instance.a(new org.koin.core.definition.a(a32, Reflection.getOrCreateKotlinClass(d.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$19, kind, emptyList23));
        module.p(aVar25);
        new Pair(module, aVar25);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$20 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$20 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$20();
        z8.c a33 = aVar2.a();
        emptyList24 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar26 = new org.koin.core.instance.a(new org.koin.core.definition.a(a33, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.messages.c.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$20, kind, emptyList24));
        module.p(aVar26);
        new Pair(module, aVar26);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$21 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$21 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$21();
        z8.c a34 = aVar2.a();
        emptyList25 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar27 = new org.koin.core.instance.a(new org.koin.core.definition.a(a34, Reflection.getOrCreateKotlinClass(o.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$21, kind, emptyList25));
        module.p(aVar27);
        new Pair(module, aVar27);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$22 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$22 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$22();
        z8.c a35 = aVar2.a();
        emptyList26 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar28 = new org.koin.core.instance.a(new org.koin.core.definition.a(a35, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.messages.a.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$22, kind, emptyList26));
        module.p(aVar28);
        new Pair(module, aVar28);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$23 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$23 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$23();
        z8.c a36 = aVar2.a();
        emptyList27 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar29 = new org.koin.core.instance.a(new org.koin.core.definition.a(a36, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.chat.a.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$23, kind, emptyList27));
        module.p(aVar29);
        new Pair(module, aVar29);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$24 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$24 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$24();
        z8.c a37 = aVar2.a();
        emptyList28 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar30 = new org.koin.core.instance.a(new org.koin.core.definition.a(a37, Reflection.getOrCreateKotlinClass(i.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$24, kind, emptyList28));
        module.p(aVar30);
        new Pair(module, aVar30);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$25 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$25 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$25();
        z8.c a38 = aVar2.a();
        emptyList29 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar31 = new org.koin.core.instance.a(new org.koin.core.definition.a(a38, Reflection.getOrCreateKotlinClass(p.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$25, kind, emptyList29));
        module.p(aVar31);
        new Pair(module, aVar31);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$26 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$26 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$26();
        z8.c a39 = aVar2.a();
        emptyList30 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar32 = new org.koin.core.instance.a(new org.koin.core.definition.a(a39, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.contact.d.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$26, kind, emptyList30));
        module.p(aVar32);
        new Pair(module, aVar32);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$27 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$27 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$27();
        z8.c a40 = aVar2.a();
        emptyList31 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar33 = new org.koin.core.instance.a(new org.koin.core.definition.a(a40, Reflection.getOrCreateKotlinClass(f.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$27, kind, emptyList31));
        module.p(aVar33);
        new Pair(module, aVar33);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$28 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$28 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$28();
        z8.c a41 = aVar2.a();
        emptyList32 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar34 = new org.koin.core.instance.a(new org.koin.core.definition.a(a41, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.contact.b.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$28, kind, emptyList32));
        module.p(aVar34);
        new Pair(module, aVar34);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$29 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$29 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$29();
        z8.c a42 = aVar2.a();
        emptyList33 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar35 = new org.koin.core.instance.a(new org.koin.core.definition.a(a42, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.contact.a.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$29, kind, emptyList33));
        module.p(aVar35);
        new Pair(module, aVar35);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$30 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$30 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$30();
        z8.c a43 = aVar2.a();
        emptyList34 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar36 = new org.koin.core.instance.a(new org.koin.core.definition.a(a43, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.contact.j.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$30, kind, emptyList34));
        module.p(aVar36);
        new Pair(module, aVar36);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$31 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$31 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$31();
        z8.c a44 = aVar2.a();
        emptyList35 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar37 = new org.koin.core.instance.a(new org.koin.core.definition.a(a44, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.members.e.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$31, kind, emptyList35));
        module.p(aVar37);
        new Pair(module, aVar37);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$32 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$32 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$32();
        z8.c a45 = aVar2.a();
        emptyList36 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar38 = new org.koin.core.instance.a(new org.koin.core.definition.a(a45, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.chat.c.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$32, kind, emptyList36));
        module.p(aVar38);
        new Pair(module, aVar38);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$33 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$33 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$33();
        z8.c a46 = aVar2.a();
        emptyList37 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar39 = new org.koin.core.instance.a(new org.koin.core.definition.a(a46, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.currentuser.h.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$33, kind, emptyList37));
        module.p(aVar39);
        new Pair(module, aVar39);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$34 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$34 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$34();
        z8.c a47 = aVar2.a();
        emptyList38 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar40 = new org.koin.core.instance.a(new org.koin.core.definition.a(a47, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.currentuser.b.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$34, kind, emptyList38));
        module.p(aVar40);
        new Pair(module, aVar40);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$35 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$35 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$35();
        z8.c a48 = aVar2.a();
        emptyList39 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar41 = new org.koin.core.instance.a(new org.koin.core.definition.a(a48, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.chat.i.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$35, kind, emptyList39));
        module.p(aVar41);
        new Pair(module, aVar41);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$36 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$36 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$36();
        z8.c a49 = aVar2.a();
        emptyList40 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar42 = new org.koin.core.instance.a(new org.koin.core.definition.a(a49, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.chat_request.f.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$36, kind, emptyList40));
        module.p(aVar42);
        new Pair(module, aVar42);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$37 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$37 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$37();
        z8.c a50 = aVar2.a();
        emptyList41 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar43 = new org.koin.core.instance.a(new org.koin.core.definition.a(a50, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.chat_request.d.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$37, kind, emptyList41));
        module.p(aVar43);
        new Pair(module, aVar43);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$38 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$38 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$38();
        z8.c a51 = aVar2.a();
        emptyList42 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar44 = new org.koin.core.instance.a(new org.koin.core.definition.a(a51, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.chat_request.c.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$38, kind, emptyList42));
        module.p(aVar44);
        new Pair(module, aVar44);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$39 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$39 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$39();
        z8.c a52 = aVar2.a();
        emptyList43 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar45 = new org.koin.core.instance.a(new org.koin.core.definition.a(a52, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.chat_request.b.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$39, kind, emptyList43));
        module.p(aVar45);
        new Pair(module, aVar45);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$40 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$40 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$40();
        z8.c a53 = aVar2.a();
        emptyList44 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar46 = new org.koin.core.instance.a(new org.koin.core.definition.a(a53, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.chat_request.e.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$40, kind, emptyList44));
        module.p(aVar46);
        new Pair(module, aVar46);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$41 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$41 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$41();
        z8.c a54 = aVar2.a();
        emptyList45 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar47 = new org.koin.core.instance.a(new org.koin.core.definition.a(a54, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.chat_request.a.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$41, kind, emptyList45));
        module.p(aVar47);
        new Pair(module, aVar47);
        ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$42 chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$42 = new ChatModuleKt$chatModule$1$invoke$$inlined$factoryOf$42();
        z8.c a55 = aVar2.a();
        emptyList46 = CollectionsKt__CollectionsKt.emptyList();
        org.koin.core.instance.a aVar48 = new org.koin.core.instance.a(new org.koin.core.definition.a(a55, Reflection.getOrCreateKotlinClass(com.im.freechat.domain.usecase.contact.e.class), null, chatModuleKt$chatModule$1$invoke$$inlined$factoryOf$42, kind, emptyList46));
        module.p(aVar48);
        new Pair(module, aVar48);
    }

    @Override // kotlin.jvm.functions.Function1
    public /* bridge */ /* synthetic */ Unit invoke(x8.a aVar) {
        a(aVar);
        return Unit.INSTANCE;
    }
}
